/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iteration1.forms;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Kazed
 */
public class MainFrame extends javax.swing.JFrame {
    private final JPanel cards;
    private final CardLayout cl;
    private JPanel currentCard;
    /**
     * Creates new form FrameMain
     * @param panel
     */
    public MainFrame(JPanel panel) {
        initComponents();
        this.cards = panel;
        cl = (CardLayout)cards.getLayout();
    }
    
    public JPanel getCards() {
        return cards;
    }
    
    public JPanel getCurrentCard() {
        return currentCard;
    }
    
    public void setCurrentCard() {
        JPanel card = null;
        for (Component comp : cards.getComponents()) {
             if (comp.isVisible() == true) {
                card = (JPanel)comp;
            }
        }
        currentCard = card;
        getContentPane().setPreferredSize(currentCard.getPreferredSize());
        if(currentCard.getName().equals("Connection")) {
            setResizable(false);
        }
        else setResizable(true);
        pack();
    }
    
    public CardLayout getCardLayout() {
        return cl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
