/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iteration1.forms;

import iteration1.DatabaseClasses.Table;
import iteration1.classesConnexion.Connexion;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kazed
 */
public class VisualizationPanel extends javax.swing.JPanel {
    private Connexion c;
    private ArrayList<Table> tables;
    /**
     * Creates new form VizualisationPanel
     */
    public VisualizationPanel() {
        initComponents();
        
        //empecher selection élément du tableau
        tblAttributes.setRowSelectionAllowed(false);
        tblAttributes.setColumnSelectionAllowed(false);
    }
    
    public void setConnection(Connexion c) {
        this.c = c;
        try {
            tables = c.getTables();
        }
        catch(SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
        getTablesList();
    }
    
    public void getTablesList() {
        
        //Remplissage de la liste des tables
        try {
            String[] tablesList = new String[tables.size()];
            int i = 0;
            for(Table t : tables) {
                tablesList[i] = t.getName();
                i++;
            }
            lstTables.setListData(tablesList);
        } 
        catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slpTables = new javax.swing.JScrollPane();
        lstTables = new javax.swing.JList<>(new DefaultListModel());
        slpAttributes = new javax.swing.JScrollPane();
        tblAttributes = new javax.swing.JTable();
        btnDisonnect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        slpTables.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        slpTables.setMaximumSize(new java.awt.Dimension(192, 384));
        slpTables.setMinimumSize(new java.awt.Dimension(192, 384));
        slpTables.setPreferredSize(new java.awt.Dimension(192, 384));

        lstTables.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lstTables.setMaximumSize(new java.awt.Dimension(160, 384));
        lstTables.setMinimumSize(new java.awt.Dimension(160, 384));
        lstTables.setPreferredSize(new java.awt.Dimension(160, 384));
        lstTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTablesMouseClicked(evt);
            }
        });
        slpTables.setViewportView(lstTables);

        slpAttributes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        slpAttributes.setMaximumSize(new java.awt.Dimension(704, 320));
        slpAttributes.setMinimumSize(new java.awt.Dimension(704, 320));
        slpAttributes.setPreferredSize(new java.awt.Dimension(704, 320));

        tblAttributes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblAttributes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Type", "Longueur", "Clé primaire", "Clé étrangère", "Not null", "Valeur par défaut", "Unique"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAttributes.setMaximumSize(new java.awt.Dimension(640, 512));
        tblAttributes.setMinimumSize(new java.awt.Dimension(640, 512));
        tblAttributes.setPreferredSize(new java.awt.Dimension(640, 512));
        slpAttributes.setViewportView(tblAttributes);

        btnDisonnect.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDisonnect.setText("Se déconnecter");
        btnDisonnect.setMaximumSize(new java.awt.Dimension(112, 32));
        btnDisonnect.setMinimumSize(new java.awt.Dimension(112, 32));
        btnDisonnect.setPreferredSize(new java.awt.Dimension(112, 32));
        btnDisonnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisonnectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Liste des tables :");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Informations de la table : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slpTables, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(btnDisonnect, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(slpAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slpTables, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slpAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnDisonnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisonnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisonnectActionPerformed
        c.close();
        
        //Vide la liste
        DefaultTableModel tm = (DefaultTableModel)tblAttributes.getModel();
        tm.setRowCount(0);
        
        //Switche l'affichage sur le JPanel ConnectionPanel 
        MainFrame f = (MainFrame)SwingUtilities.getRoot(this);
        f.getCardLayout().first(f.getCards());
        f.setCurrentCard();
    }//GEN-LAST:event_btnDisonnectActionPerformed

    private void lstTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTablesMouseClicked

        //on recup le modele du Jtable
        DefaultTableModel tableModel = (DefaultTableModel)tblAttributes.getModel();
        tableModel.setRowCount(0);

        //on rempli le Jtable avec les infos de la table grace a getColonnes(nomTable);
        try {
            ArrayList<Object[]> tab = c.getColonnes(lstTables.getSelectedValue());
            for(int i = 0; i < tab.size(); i++){
                tableModel.addRow(tab.get(i));
            }
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_lstTablesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisonnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> lstTables;
    private javax.swing.JScrollPane slpAttributes;
    private javax.swing.JScrollPane slpTables;
    private javax.swing.JTable tblAttributes;
    // End of variables declaration//GEN-END:variables
}
